name: 'Teleport Auth Kubernetes'
description: 'Uses Machine ID to fetch credentials for use with a Kubernetes cluster. Automatically configure `KUBE_CONFIG` environment variable so invocations of `kubectl` and similar tools work as expected.'
author: 'Gravitational Inc.'
inputs:
  version:
    required: true
    description: 'Specify the Teleport version without the preceding "v"'
runs:
  using: 'node16'
  main: '../dist/auth-k8s/index.js'
